# -*- coding: utf-8 -*-
"""classifying_iris_species.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlSjkqeXZWNszOTK0dLGDumpoXcYWes9
"""

#making model iris dataset model
#loading the model from sklearn
from sklearn.datasets import load_iris
iris_dataset=load_iris()
print(type(iris_dataset))
print("keys are",iris_dataset.keys())

#descr
print("DESCRIPTION{}".format(iris_dataset['DESCR'][:199]))

#data
print("data\n{}".format(iris_dataset['data'][:10]))

#target_names
print(iris_dataset['target_names'])

#using train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

#using knn model
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)

#predict
y_pred=knn.predict(X_test)

#score
print("score\n{:.2f}".format(knn.score(X_test,y_test)))
